=begin
#Assessment Network API

#> Stores content for the Assessment Network Requests to this API must include application/json in the `Accept` header. All endpoints require an API key to be passed in the request header.  API keys can be obtained by members at www.a15k.org. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

# Common files
require 'a15k_client/api_client'
require 'a15k_client/api_error'
require 'a15k_client/version'
require 'a15k_client/configuration'

# Models
require 'a15k_client/models/assessment'
require 'a15k_client/models/assessment_input'
require 'a15k_client/models/assessment_input_questions'
require 'a15k_client/models/assessment_input_solutions'
require 'a15k_client/models/asset'
require 'a15k_client/models/error'
require 'a15k_client/models/format'
require 'a15k_client/models/format_input'
require 'a15k_client/models/inline_response_200'
require 'a15k_client/models/inline_response_200_1'
require 'a15k_client/models/inline_response_200_2'
require 'a15k_client/models/question'
require 'a15k_client/models/solution'

# APIs
require 'a15k_client/api/assessments_api'
require 'a15k_client/api/formats_api'

module A15kClient
  class << self
    # Customize default settings for the SDK using block.
    #   A15kClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
