=begin
#Assessment Network API

#> Stores content for the Assessment Network Requests to this API must include application/json in the `Accept` header. All endpoints require an API key to be passed in the request header.  API keys can be obtained by members at www.a15k.org. 

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for A15kClient::FormatsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FormatsApi' do
  before do
    # run before each test
    @instance = A15kClient::FormatsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FormatsApi' do
    it 'should create an instance of FormatsApi' do
      expect(@instance).to be_instance_of(A15kClient::FormatsApi)
    end
  end

  # unit tests for create_format
  # create  a format
  # 
  # @param format Format to be created
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse2001]
  describe 'create_format test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_formats
  # Get all formats
  # List all known formats
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'get_formats test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
