# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.


development:
  base_url: a15k.org
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', 'af8b9fab193891504598d3720c18c3109c4756fd6c3dc53c01d683b02d649cb384cc0fd6dac3f1812939bde7c9634b2633833cf209a9b11a13c0bf3c9cd00404') %>
  metadata_api:
    url: http://localhost:3000
    token: <%= ENV['A15K_METADATA_TOKEN'] || 'a15k_insecure_token' %>
    application_uuid: <%= ENV['A15K_METADATA_APP_UUID'] %>
    stub: <%= ENV.fetch('A15K_METADATA_STUB', true) %>
  interactions_api:
    scheme: 'http'
    url: <%= ENV.fetch('A15K_INTERACTIONS_URL', 'http://localhost:4003') %>
    admin_api_token: <%= ENV.fetch('A15K_API_TOKEN', 'abcd123456789') %>
    stub: <%= ENV.fetch('A15K_INTERACTIONS_STUB', true) %>
  openstax:
    accounts:
      client_id: <%= ENV["OPENSTAX_ACCOUNTS_CLIENT_ID"] %>
      secret: <%= ENV["OPENSTAX_ACCOUNTS_SECRET"] %>
      url: <%= ENV["OPENSTAX_ACCOUNTS_URL"] || 'http://localhost:2999' %>
      stub: <%= ENV.fetch("OPENSTAX_ACCOUNTS_STUB", true) %>

test:
  base_url: a15k.org
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', 'af8b9fab193891504598d3720c18c3109c4756fd6c3dc53c01d683b02d649cb384cc0fd6dac3f1812939bde7c9634b2633833cf209a9b11a13c0bf3c9cd00404') %>
  metadata_api:
    url: http://localhost:3000
    token: <%= ENV['A15K_METADATA_TOKEN'] || 'a15k_insecure_token' %>
    application_uuid: <%= ENV['A15K_METADATA_APP_UUID'] %>
    stub: <%= ENV.fetch('A15K_METADATA_STUB', true) %>
  interactions_api:
    scheme: 'http'
    url: <%= ENV.fetch('A15K_INTERACTIONS_URL', 'http://localhost:4003') %>
    admin_api_token: <%= ENV.fetch('A15K_API_TOKEN', 'abcd123456789') %>
    stub: <%= ENV.fetch('A15K_INTERACTIONS_STUB', true) %>
  openstax:
    accounts:
      client_id: <%= ENV["OPENSTAX_ACCOUNTS_CLIENT_ID"] %>
      secret: <%= ENV["OPENSTAX_ACCOUNTS_SECRET"] %>
      url: <%= ENV["OPENSTAX_ACCOUNTS_URL"] || 'http://localhost:2999' %>
      stub: <%= ENV.fetch("OPENSTAX_ACCOUNTS_STUB", true) %>

# Deployment template for production secrets

production:
  secret_key_base: random(hex,80)
  base_url: "https://{{ domain }}"
  database:
    host: "{{ database_host }}"
    port: "{{ database_port }}"
    username: "{{ database_username }}"
    password: "{{ database_password }}"
    dbname: "{{ database_name }}"
