/*
 * Assessment Network API
 * > Stores content for the Assessment Network  API Version is specified in the URL path as `api/<version>/resource` Version will default to the latest if it's ommited  All endpoints require an API key to be passed in the request header. API keys can be obtained by members at www.a15k.org. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.a15k.client.v1.client.api;

import org.a15k.client.v1.client.ApiException;
import org.a15k.client.v1.client.model.Assessment;
import org.a15k.client.v1.client.model.Error;
import org.a15k.client.v1.client.model.InlineResponse2004;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AssessmentsApi
 */
@Ignore
public class AssessmentsApiTest {

    private final AssessmentsApi api = new AssessmentsApi();

    
    /**
     * create an assessment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAssessmentTest() throws ApiException {
        Assessment assessment = null;
        InlineResponse2004 response = api.createAssessment(assessment);

        // TODO: test validations
    }
    
    /**
     * Retrieve an assessment
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAssessmentTest() throws ApiException {
        Integer id = null;
        InlineResponse2004 response = api.getAssessment(id);

        // TODO: test validations
    }
    
    /**
     * Search for assessments
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchAssessmentsTest() throws ApiException {
        String query = null;
        String page = null;
        String perPage = null;
        InlineResponse2004 response = api.searchAssessments(query, page, perPage);

        // TODO: test validations
    }
    
}
