/*
 * Assessment Network API
 * > Stores content for the Assessment Network  API Version is specified in the URL path as `api/<version>/resource` Version will default to the latest if it's ommited  All endpoints require an API key to be passed in the request header. API keys can be obtained by members at www.a15k.org. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.a15k.client.v1.client.api;

import org.a15k.client.v1.client.ApiException;
import org.a15k.client.v1.client.model.Error;
import org.a15k.client.v1.client.model.InlineResponse200;
import org.a15k.client.v1.client.model.InlineResponse2001;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * add a newly created user account to a member
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void claimUserTest() throws ApiException {
        String email = null;
         role = null;
        InlineResponse2001 response = api.claimUser(email, role);

        // TODO: test validations
    }
    
    /**
     * remove a user from member
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        InlineResponse2001 response = api.deleteUser();

        // TODO: test validations
    }
    
    /**
     * Get all users for the member
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsersTest() throws ApiException {
        InlineResponse200 response = api.getUsers();

        // TODO: test validations
    }
    
    /**
     * alter a user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
         role = null;
        InlineResponse2001 response = api.updateUser(role);

        // TODO: test validations
    }
    
}
