/*
 * Assessment Network API
 * > Stores content for the Assessment Network  API Version is specified in the URL path as `api/<version>/resource` Version will default to the latest if it's ommited  All endpoints require an API key to be passed in the request header. API keys can be obtained by members at www.a15k.org. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.a15k.client.v1.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.a15k.client.v1.client.model.AssessmentMetadata;
import org.a15k.client.v1.client.model.Variant;

/**
 * The umbrella record for all things related to an assessment.
 */
@ApiModel(description = "The umbrella record for all things related to an assessment.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-14T10:14:33.057-06:00")
public class Assessment {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("created_at")
  private String createdAt = null;

  @SerializedName("source_identifier")
  private String sourceIdentifier = null;

  @SerializedName("source_version")
  private String sourceVersion = null;

  @SerializedName("a15k_identifier")
  private UUID a15kIdentifier = null;

  @SerializedName("a15k_version")
  private Integer a15kVersion = null;

  @SerializedName("metadata")
  private AssessmentMetadata metadata = null;

  @SerializedName("variants")
  private List<Variant> variants = null;

  public Assessment id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * A UUID for this specific assessment version
   * @return id
  **/
  @ApiModelProperty(required = true, value = "A UUID for this specific assessment version")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public Assessment createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public Assessment sourceIdentifier(String sourceIdentifier) {
    this.sourceIdentifier = sourceIdentifier;
    return this;
  }

   /**
   * A member-controlled identifier that is shared between all versions of this assessment in the member&#39;s assessment repository (the source).  If contributing a new version of a previous contribution, provide the source_identifier you provided for other versions or the a15k_identifier from those versions. 
   * @return sourceIdentifier
  **/
  @ApiModelProperty(value = "A member-controlled identifier that is shared between all versions of this assessment in the member's assessment repository (the source).  If contributing a new version of a previous contribution, provide the source_identifier you provided for other versions or the a15k_identifier from those versions. ")
  public String getSourceIdentifier() {
    return sourceIdentifier;
  }

  public void setSourceIdentifier(String sourceIdentifier) {
    this.sourceIdentifier = sourceIdentifier;
  }

  public Assessment sourceVersion(String sourceVersion) {
    this.sourceVersion = sourceVersion;
    return this;
  }

   /**
   * A member-controlled value identifying this assessment&#39;s version in the member&#39;s assessment repository (the source).
   * @return sourceVersion
  **/
  @ApiModelProperty(value = "A member-controlled value identifying this assessment's version in the member's assessment repository (the source).")
  public String getSourceVersion() {
    return sourceVersion;
  }

  public void setSourceVersion(String sourceVersion) {
    this.sourceVersion = sourceVersion;
  }

  public Assessment a15kIdentifier(UUID a15kIdentifier) {
    this.a15kIdentifier = a15kIdentifier;
    return this;
  }

   /**
   * An a15k-provided UUID that is shared between all versions of this assessment within the network. If contributing a new version of a previous contribution, provide this a15k_identifier or the source_identifier you provided for the other versions. 
   * @return a15kIdentifier
  **/
  @ApiModelProperty(required = true, value = "An a15k-provided UUID that is shared between all versions of this assessment within the network. If contributing a new version of a previous contribution, provide this a15k_identifier or the source_identifier you provided for the other versions. ")
  public UUID getA15kIdentifier() {
    return a15kIdentifier;
  }

  public void setA15kIdentifier(UUID a15kIdentifier) {
    this.a15kIdentifier = a15kIdentifier;
  }

  public Assessment a15kVersion(Integer a15kVersion) {
    this.a15kVersion = a15kVersion;
    return this;
  }

   /**
   * An a15k-provided number identifying which version this assessment is.
   * @return a15kVersion
  **/
  @ApiModelProperty(required = true, value = "An a15k-provided number identifying which version this assessment is.")
  public Integer getA15kVersion() {
    return a15kVersion;
  }

  public void setA15kVersion(Integer a15kVersion) {
    this.a15kVersion = a15kVersion;
  }

  public Assessment metadata(AssessmentMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @ApiModelProperty(value = "")
  public AssessmentMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(AssessmentMetadata metadata) {
    this.metadata = metadata;
  }

  public Assessment variants(List<Variant> variants) {
    this.variants = variants;
    return this;
  }

  public Assessment addVariantsItem(Variant variantsItem) {
    if (this.variants == null) {
      this.variants = new ArrayList<Variant>();
    }
    this.variants.add(variantsItem);
    return this;
  }

   /**
   * Get variants
   * @return variants
  **/
  @ApiModelProperty(value = "")
  public List<Variant> getVariants() {
    return variants;
  }

  public void setVariants(List<Variant> variants) {
    this.variants = variants;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Assessment assessment = (Assessment) o;
    return Objects.equals(this.id, assessment.id) &&
        Objects.equals(this.createdAt, assessment.createdAt) &&
        Objects.equals(this.sourceIdentifier, assessment.sourceIdentifier) &&
        Objects.equals(this.sourceVersion, assessment.sourceVersion) &&
        Objects.equals(this.a15kIdentifier, assessment.a15kIdentifier) &&
        Objects.equals(this.a15kVersion, assessment.a15kVersion) &&
        Objects.equals(this.metadata, assessment.metadata) &&
        Objects.equals(this.variants, assessment.variants);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, sourceIdentifier, sourceVersion, a15kIdentifier, a15kVersion, metadata, variants);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Assessment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    sourceIdentifier: ").append(toIndentedString(sourceIdentifier)).append("\n");
    sb.append("    sourceVersion: ").append(toIndentedString(sourceVersion)).append("\n");
    sb.append("    a15kIdentifier: ").append(toIndentedString(a15kIdentifier)).append("\n");
    sb.append("    a15kVersion: ").append(toIndentedString(a15kVersion)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    variants: ").append(toIndentedString(variants)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

